import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import TanstackQuery from './libs/tanstack-query'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Home Page',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <TanstackQuery>
          <div>{children}</div>
        </TanstackQuery>
      </body>
    </html>
  )
}
